services:
  - type: web
    name: djelis-backend
    env: docker
    region: frankfurt
    plan: starter
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health/live
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
